blogsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
]

frontend/urls.py
from django.urls import path
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.PostList.as_view(), name = 'index'),
    path('about/', views.AboutPage, name='about'),
    path('login/', admin.site.urls, name='login'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class MiscContent(models.Model):
    name = models.CharField(max_length=50, default="")
    content = models.TextField()

    def __str__(self):
        return self.name

frontend/views.py
from django.shortcuts import render
from django.views import generic
from .models import *

# Create your views here.

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post.html'

def AboutPage(request):
    context = {
        'content': MiscContent.objects.get(name='About').content
    }

    return render(request, 'about.html', context)

frontend/templates/about.html
{% extends "base.html" %}
{% load markdown_extras %}
{% load static %}

{% block title %}
About
{% endblock title %}

{% block content %}

<div class='post-details'>
    <p>{{ content | markdown | safe }}</p>
</div>

{% endblock content %}

frontend/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, shrink-to-fit=no">

        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    </head>

    <body>
        <nav>
            <label for="hamburger">&#9776;</label>
            <input type="checkbox" id="hamburger"/>

            <a href="/">Home</a>
            <a href="/about">About</a>
            <a href="/login">Login</a>
        </nav>
        <main>
            {% block content %}{% endblock %}
        </main>

    </body>
</html>

frontend/templates/index.html
{% extends "base.html" %}
{% load markdown_extras %}
{% load static %}

{% block title %}
Homepage
{% endblock title %}

{% block content %}

<div class='posts-view'>
    {% for post in post_list %}
        <div class='post-preview' onclick="location.href='{% url 'post_detail' post.slug %}'">
            <p class='post-title'>{{ post.title }}</p>
            <p>by {{ post.author }}</p>
            <p>{{ post.updated_on }} | {{ post.created_on }}</p>
            <p>{{ post.content | markdown | safe }}</p>
        </div>
    {% endfor %}
</div>

{% endblock content %}

frontend/templates/post.html
{% extends "base.html" %}
{% load markdown_extras %}
{% load static %}

{% block title %}
{{post.title}}
{% endblock title %}

{% block content %}

<h1>Here are the post details</h1>

        <div class='post-details'>
            <p class='post-title'>{{ post.title }}</p>
            <p>by {{ post.author }}</p>
            <p>{{ post.updated_on }} | {{ post.created_on }}</p>
            <p>{{ post.content | markdown | safe }}</p>
        </div>

{% endblock content %}